config/routes.rb
HackerCast::Application.routes.draw do
  get "home/index"

  get "broadcasts/new"
  post "broadcasts/new"

  get "broadcasts/rx/:key", to: 'broadcasts#rx'
  get "broadcasts/tx/:key", to: 'broadcasts#tx'

  root :to => 'broadcasts#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/broadcasts_controller.rb
require 'securerandom'

class BroadcastsController < ApplicationController
  def new
    if request.post?
      random_channel_id = SecureRandom.urlsafe_base64
      redirect_to  :action => "tx", :key => random_channel_id
    end
  end

  def rx

  end

  def tx
    @key = params[:key]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/broadcasts/new.html.erb
<div class="row">
  <div class="twelve columns centered" style='text-align: center'>
    <h2>Create a new broadcast!</h2>
    <hr />
  </div>
</div>

<div class="row">
  <div class="twelve columns centered" style='text-align: center'>
    <%= form_tag(broadcasts_new_url) do -%>
        <div><%= submit_tag 'Action!', :class => "large success button" %>
    <% end %>
  </div>
</div>

app/views/broadcasts/rx.html.erb
<meta name="room_key" content="<%= @key %>">
<div class="row">
  <div class="twelve columns">
    <h2>Recieving....</h2>
    <hr />
  </div>
</div>


<div id="transmit_container">
  <video id='preview' autoplay></video>
  <video id='viewer' autoplay></video>
</div>

app/views/broadcasts/tx.html.erb
<meta name="room_key" content="<%= @key %>">
<div class="row">
  <div class="twelve columns">
    <h2>Transmitting....</h2>
    <hr />
  </div>
</div>


<div id="transmit_container">
  <video id='preview' autoplay></video>
  <video id='viewer' autoplay></video>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="twelve columns">
    <h2>Start Broadcasting!</h2>
    <hr />
  </div>
</div>


<div class="row">
  <div class="five columns centered">
    <p><%= link_to "ACTION!", broadcasts_new_url, :class => "large success button"%></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerCast</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="twelve columns">
      <%= yield %>
    </div>
  </div>
</html>